segmentor_path: './models/segmentor/two_ds_DICE.h5'
segmentor_indims:
  - 128
  - 80
classifier_path: './models/classifier/naive_model_basic.h5'
classifier_indims:
  - 200
  - 200
class_dict_path: './models/classifier/classes.pickle'